import { STUDIO_CHAIN_ID } from "./config";
export type EthereumProvider = { request(args:{method:string;params?:unknown[]}): Promise<unknown>; on?(event:string, fn:(value: unknown)=>void):void; removeListener?(event:string,fn:(value:unknown)=>void):void; isMetaMask?:boolean };
export type WalletOption={id:string;name:string;rdns:string;provider:EthereumProvider}; type Announce={detail:{info:{name:string;rdns:string;uuid:string};provider:EthereumProvider}};
let selectedId=""; let discovered:WalletOption[]=[];
const identifier=(provider:EthereumProvider,info?:{uuid?:string;name?:string;rdns?:string})=>info?.uuid??info?.rdns??(provider.isMetaMask?"metamask":"injected");
export function discoverWallets():WalletOption[]{if(typeof window==="undefined")return [];const add=(provider:EthereumProvider,info?:{uuid?:string;name?:string;rdns?:string})=>{const id=identifier(provider,info);if(!discovered.some(item=>item.id===id))discovered=[...discovered,{id,name:info?.name??(provider.isMetaMask?"MetaMask":"Injected wallet"),rdns:info?.rdns??(provider.isMetaMask?"io.metamask":"unknown"),provider}]};const announce=(event:Event)=>{const detail=(event as CustomEvent<Announce["detail"]>).detail;if(detail?.provider)add(detail.provider,detail.info)};window.addEventListener("eip6963:announceProvider",announce);window.dispatchEvent(new Event("eip6963:requestProvider"));if(window.ethereum)add(window.ethereum);return discovered;}
export function walletOptions(){return discovered;}
export function selectWallet(id:string){selectedId=id;}
export function selectedWallet():WalletOption|null{const all=discoverWallets();return all.find(item=>item.id===selectedId)??all.find(item=>item.provider.isMetaMask)??all[0]??null;}
export function injectedProvider():EthereumProvider|null{return selectedWallet()?.provider??null;}
export async function walletChain(provider: EthereumProvider) { const id=await provider.request({method:"eth_chainId"}); return typeof id === "string" ? Number.parseInt(id,16) : 0; }
export async function requireStudioNet(provider: EthereumProvider) { if (await walletChain(provider)!==STUDIO_CHAIN_ID) throw new Error("WRONG_NETWORK: switch wallet to GenLayer StudioNet (61999)"); }
export async function withSelectedProviderAsWindow<T>(provider:EthereumProvider,work:()=>Promise<T>):Promise<T>{const prior=window.ethereum;window.ethereum=provider;try{return await work();}finally{window.ethereum=prior;}}
const copy=(value:unknown,seen=new WeakSet<object>()):unknown=>{if(value===null||typeof value!=="object")return value;if(seen.has(value as object))return "[circular]";seen.add(value as object);if(Array.isArray(value))return value.map(item=>copy(item,seen));const out:Record<string,unknown>={};for(const key of Object.getOwnPropertyNames(value)){try{out[key]=copy((value as Record<string,unknown>)[key],seen)}catch{out[key]="[unreadable]"}}return out;};
export function normalizeWalletError(error:unknown,stage:string):string{const snapshot=copy(error);const record=snapshot&&typeof snapshot==="object"?snapshot as Record<string,unknown>:undefined;const message=typeof record?.message==="string"?record.message:typeof record?.cause==="object"&&record.cause&&typeof (record.cause as Record<string,unknown>).message==="string"?(record.cause as Record<string,unknown>).message:typeof error==="string"?error:JSON.stringify(snapshot);return `${stage}: ${message}\nDetails: ${JSON.stringify(snapshot)}`;}
declare global { interface Window { ethereum?: EthereumProvider; } }
