import {contractRead} from "./contract"; import {u256Id} from "./ids"; import type {Cluster,Feature,Layer,Related} from "./types";
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("MALFORMED_RESPONSE");return value as Record<string,unknown>;}
export async function getFeature(id:string):Promise<Feature>{return object(await contractRead("get_feature",[u256Id(id)])) as unknown as Feature;}
export async function getLayer(id:string):Promise<Layer>{return object(await contractRead("get_layer",[u256Id(id)])) as unknown as Layer;}
export async function getCluster(id:string):Promise<Cluster>{return object(await contractRead("get_cluster",[u256Id(id)])) as unknown as Cluster;}
async function ids(method:string,args:unknown[]):Promise<string[]>{const data=await contractRead(method,args);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data.map(String);}
export async function getClusters(offset=0,limit=32):Promise<Cluster[]>{const data=await contractRead("get_clusters",[offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data.map(object) as unknown as Cluster[];}
export async function getClusterEntries(offset=0,limit=32):Promise<{id:string;cluster:Cluster}[]>{const [entries,entityIds]=await Promise.all([getClusters(offset,limit),ids("get_cluster_ids",[offset,limit])]);if(entries.length!==entityIds.length)throw new Error("MALFORMED_RESPONSE");return entries.map((cluster,index)=>({id:entityIds[index],cluster}));}
export async function getLayerClusters(id:string,offset=0,limit=32):Promise<Cluster[]>{const data=await contractRead("get_layer_clusters",[u256Id(id),offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data.map(object) as unknown as Cluster[];}
export async function getLayers(offset=0,limit=32):Promise<Layer[]>{const data=await contractRead("get_layers",[offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data.map(object) as unknown as Layer[];}
export async function getLayerEntries(offset=0,limit=32):Promise<{id:string;layer:Layer}[]>{const [entries,entityIds]=await Promise.all([getLayers(offset,limit),ids("get_layer_ids",[offset,limit])]);if(entries.length!==entityIds.length)throw new Error("MALFORMED_RESPONSE");return entries.map((layer,index)=>({id:entityIds[index],layer}));}
export async function getLayerFeatures(id:string,offset=0,limit=32):Promise<Feature[]>{const data=await contractRead("get_layer_features",[u256Id(id),offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data.map(object) as unknown as Feature[];}
export async function getLayerFeatureEntries(id:string,offset=0,limit=32):Promise<{id:string;feature:Feature}[]>{const [entries,entityIds]=await Promise.all([getLayerFeatures(id,offset,limit),ids("get_layer_feature_ids",[u256Id(id),offset,limit])]);if(entries.length!==entityIds.length)throw new Error("MALFORMED_RESPONSE");return entries.map((feature,index)=>({id:entityIds[index],feature}));}
export async function getHistory(id:string):Promise<unknown[]>{const data=await contractRead("get_feature_history",[u256Id(id),0,32]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data;}
export async function related(id:string):Promise<Related[]>{const data=await contractRead("preview_related",[u256Id(id),8]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE");return data.map(item=>typeof item==="string"?JSON.parse(item):item) as Related[];}
