import {contractRead} from "./contract";
import {u256Id} from "./ids";
import {decodeAddress,decodeBool,decodeJsonString,decodeObject,decodeScalarString,decodeString,decodeU256,decodeU8} from "./decoders";
import type {Cluster,Feature,Layer,Related} from "./types";

function normalizeFeature(value:unknown):Feature{const raw=decodeObject(value,"feature");return {active:decodeBool(raw.active,"feature.active"),attrs_json:decodeJsonString(raw.attrs_json,"feature.attrs_json"),coarse_geohash:decodeString(raw.coarse_geohash,"feature.coarse_geohash"),feature_key:decodeString(raw.feature_key,"feature.feature_key"),geometry_digest:decodeString(raw.geometry_digest,"feature.geometry_digest"),layer_id:decodeU256(raw.layer_id,"feature.layer_id"),version:decodeU256(raw.version,"feature.version")};}
function normalizeLayer(value:unknown):Layer{const raw=decodeObject(value,"layer");return {steward:decodeAddress(raw.steward,"layer.steward"),name:decodeString(raw.name,"layer.name"),charter_url:decodeString(raw.charter_url,"layer.charter_url"),charter_digest:decodeString(raw.charter_digest,"layer.charter_digest"),bbox_json:decodeJsonString(raw.bbox_json,"layer.bbox_json"),version:decodeU256(raw.version,"layer.version"),feature_count:decodeU256(raw.feature_count,"layer.feature_count")};}
function normalizeCluster(value:unknown):Cluster{const raw=decodeObject(value,"cluster");return {submitter:decodeAddress(raw.submitter,"cluster.submitter"),layer_id:decodeU256(raw.layer_id,"cluster.layer_id"),feature_id:decodeU256(raw.feature_id,"cluster.feature_id"),attribute:decodeString(raw.attribute,"cluster.attribute"),value:decodeString(raw.value,"cluster.value"),bundle_url:decodeString(raw.bundle_url,"cluster.bundle_url"),bundle_digest:decodeString(raw.bundle_digest,"cluster.bundle_digest"),geohash:decodeString(raw.geohash,"cluster.geohash"),base_version:decodeU256(raw.base_version,"cluster.base_version"),status:decodeU8(raw.status,"cluster.status"),related_json:decodeJsonString(raw.related_json,"cluster.related_json"),reason_code:decodeString(raw.reason_code,"cluster.reason_code"),rationale:decodeString(raw.rationale,"cluster.rationale")};}
function normalizeRelated(value:unknown):Related{const raw=decodeObject(value,"related");return {delta_id:decodeU256(raw.delta_id,"related.delta_id"),distance:decodeScalarString(raw.distance,"related.distance"),...(raw.status===undefined?{}:{status:decodeString(raw.status,"related.status")}),...(raw.summary===undefined?{}:{summary:decodeString(raw.summary,"related.summary")})};}
export async function getFeature(id:string):Promise<Feature>{return normalizeFeature(await contractRead("get_feature",[u256Id(id)]));}
export async function getLayer(id:string):Promise<Layer>{return normalizeLayer(await contractRead("get_layer",[u256Id(id)]));}
export async function getCluster(id:string):Promise<Cluster>{return normalizeCluster(await contractRead("get_cluster",[u256Id(id)]));}
async function ids(method:string,args:unknown[]):Promise<string[]>{const data=await contractRead(method,args);if(!Array.isArray(data))throw new Error(`MALFORMED_RESPONSE: ${method}`);return data.map((value,index)=>decodeU256(value,`${method}[${index}]`));}
export async function getClusters(offset=0,limit=32):Promise<Cluster[]>{const data=await contractRead("get_clusters",[offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE: get_clusters");return data.map(normalizeCluster);}
export async function getClusterEntries(offset=0,limit=32):Promise<{id:string;cluster:Cluster}[]>{const [entries,entityIds]=await Promise.all([getClusters(offset,limit),ids("get_cluster_ids",[offset,limit])]);if(entries.length!==entityIds.length)throw new Error("MALFORMED_RESPONSE: get_cluster_ids");return entries.map((cluster,index)=>({id:entityIds[index],cluster}));}
export async function getLayerClusters(id:string,offset=0,limit=32):Promise<Cluster[]>{const data=await contractRead("get_layer_clusters",[u256Id(id),offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE: get_layer_clusters");return data.map(normalizeCluster);}
export async function getLayers(offset=0,limit=32):Promise<Layer[]>{const data=await contractRead("get_layers",[offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE: get_layers");return data.map(normalizeLayer);}
export async function getLayerEntries(offset=0,limit=32):Promise<{id:string;layer:Layer}[]>{const [entries,entityIds]=await Promise.all([getLayers(offset,limit),ids("get_layer_ids",[offset,limit])]);if(entries.length!==entityIds.length)throw new Error("MALFORMED_RESPONSE: get_layer_ids");return entries.map((layer,index)=>({id:entityIds[index],layer}));}
export async function getLayerFeatures(id:string,offset=0,limit=32):Promise<Feature[]>{const data=await contractRead("get_layer_features",[u256Id(id),offset,limit]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE: get_layer_features");return data.map(normalizeFeature);}
export async function getLayerFeatureEntries(id:string,offset=0,limit=32):Promise<{id:string;feature:Feature}[]>{const [entries,entityIds]=await Promise.all([getLayerFeatures(id,offset,limit),ids("get_layer_feature_ids",[u256Id(id),offset,limit])]);if(entries.length!==entityIds.length)throw new Error("MALFORMED_RESPONSE: get_layer_feature_ids");return entries.map((feature,index)=>({id:entityIds[index],feature}));}
export async function getHistory(id:string):Promise<unknown[]>{const data=await contractRead("get_feature_history",[u256Id(id),0,32]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE: get_feature_history");return data;}
export async function related(id:string):Promise<Related[]>{const data=await contractRead("preview_related",[u256Id(id),8]);if(!Array.isArray(data))throw new Error("MALFORMED_RESPONSE: preview_related");return data.map(item=>normalizeRelated(typeof item==="string"?JSON.parse(item):item));}
