"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Shell} from "../../components/shell";
import {TransactionRail} from "../../components/transaction-rail";
import {Unavailable} from "../../components/live";
import {contractWrite} from "../../lib/genlayer/contract";
import {getLayerEntries} from "../../lib/genlayer/data-source";
import type {Layer,TxStage} from "../../lib/genlayer/types";
const digest=/^sha256:[0-9a-f]{64}$/; const active=(stage:TxStage)=>["validating","signing","submitted","pending"].includes(stage);
export default function Layers(){const router=useRouter();const [layers,setLayers]=useState<{id:string;layer:Layer}[]>([]),[name,setName]=useState(""),[url,setUrl]=useState(""),[charterDigest,setCharterDigest]=useState(""),[bbox,setBbox]=useState('{"min_lat":0,"max_lat":0,"min_lng":0,"max_lng":0}'),[stage,setStage]=useState<TxStage>("idle"),[hash,setHash]=useState(""),[message,setMessage]=useState("");const refresh=()=>getLayerEntries().then(setLayers).catch(e=>setMessage(e instanceof Error?e.message:"Unavailable"));useEffect(()=>{refresh();},[]);
async function create(){try{setMessage("");const parsed=JSON.parse(bbox);if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error("Bounding box must be a JSON object");if(!name.trim())throw new Error("Layer name is required");if(!url.startsWith("https://"))throw new Error("Charter URL must use HTTPS");if(!digest.test(charterDigest.trim()))throw new Error("Charter digest must be sha256:<64 lowercase hex>");await contractWrite("create_layer",[name.trim(),url,charterDigest.trim(),parsed],(next,tx,detail)=>{setStage(next);if(tx)setHash(tx);if(detail)setMessage(detail)});await refresh();const newest=(await getLayerEntries()).at(-1);if(newest)router.push(`/layers/${newest.id}`);}catch(e){setStage("error");setMessage(e instanceof Error?e.message:"Layer creation failed");}}
return <Shell><section className="table-sheet"><p className="eyebrow">AUTHORITATIVE LAYERS</p><h1>Layer registry</h1>{message&&stage==="idle"?<Unavailable message={message}/>:layers.length?layers.map(({id,layer})=><article key={id}><Link href={`/layers/${id}`}>{layer.name}</Link><p>Layer {id} · {layer.feature_count} registered features</p><small>Steward {layer.steward}</small></article>):<p>No layers have been created on this contract yet.</p>}<h2>Create layer</h2><p>Creates an authoritative, empty layer. The connected wallet becomes its steward.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Public charter URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Charter SHA-256 digest<input value={charterDigest} onChange={e=>setCharterDigest(e.target.value)} placeholder="sha256:…"/></label><label>Bounding box (JSON object)<textarea value={bbox} onChange={e=>setBbox(e.target.value)}/></label><button disabled={active(stage)} onClick={create}>Create layer</button><TransactionRail stage={stage} hash={hash} message={message}/></section></Shell>}
