"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {Shell} from "../../../components/shell";
import {TransactionRail} from "../../../components/transaction-rail";
import {Unavailable} from "../../../components/live";
import {contractWrite} from "../../../lib/genlayer/contract";
import {getLayer,getLayerFeatureEntries} from "../../../lib/genlayer/data-source";
import type {Layer,TxStage} from "../../../lib/genlayer/types";
export default function LayerPage({params}:{params:Promise<{id:string}>}){const [id,setId]=useState("");const [layer,setLayer]=useState<Layer>();const [features,setFeatures]=useState<{id:string;feature:import("../../../lib/genlayer/types").Feature}[]>([]);const [key,setKey]=useState("");const [attrs,setAttrs]=useState('{"name":"","status":"OPEN"}');const [geometry,setGeometry]=useState("sha256:"+"0".repeat(64));const [stage,setStage]=useState<TxStage>("idle");const [hash,setHash]=useState("");const [error,setError]=useState("");const refresh=async(next:string)=>{setLayer(await getLayer(next));setFeatures(await getLayerFeatureEntries(next));};useEffect(()=>{params.then(p=>{setId(p.id);refresh(p.id).catch(e=>setError(e instanceof Error?e.message:"Unavailable"));});},[params]);async function register(){try{const parsed=JSON.parse(attrs);if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error("Attributes must be a JSON object");await contractWrite("register_feature",[id,key,parsed,geometry],(s,h,m)=>{setStage(s);setHash(h??"");if(m)setError(m)});await refresh(id)}catch(e){setError(e instanceof Error?e.message:"Feature registration failed")}}return <Shell><TransactionRail stage={stage} hash={hash} message={error}/>{error&&!layer?<Unavailable message={error}/>:<section className="sheet"><p className="eyebrow">LAYER {id}</p><h1>{layer?.name??"Reading layer…"}</h1><p>Registering a feature is restricted by the contract to this layer’s steward wallet.</p><h2>Registered features</h2>{features.length?features.map(({id:featureId,feature})=><article key={featureId}><Link href={`/features/${featureId}`}>{feature.feature_key}</Link><p>Feature {featureId} · version {feature.version}</p></article>):<p>No features yet.</p>}<h2>Steward: register feature</h2><label>Feature key<input value={key} onChange={e=>setKey(e.target.value)}/></label><label>Initial attributes (JSON object)<textarea value={attrs} onChange={e=>setAttrs(e.target.value)}/></label><label>Geometry digest<input value={geometry} onChange={e=>setGeometry(e.target.value)}/></label><button disabled={stage!=="idle"} onClick={register}>Register feature</button></section>}</Shell>}
