"use client";
import {useEffect,useRef,useState} from "react";
import {Shell} from "../../components/shell";
import {TransactionRail} from "../../components/transaction-rail";
import {contractWrite} from "../../lib/genlayer/contract";
import {u256Id} from "../../lib/genlayer/ids";
import {createSubmissionLock} from "../../lib/genlayer/submission-lock";
import {getLayerEntries,getLayerFeatureEntries} from "../../lib/genlayer/data-source";
import type {Feature,Layer,TxStage} from "../../lib/genlayer/types";
const attributes=["name","status","access","category","direction","geometry_note"];
const geohashPattern=/^[0123456789bcdefghjkmnpqrstuvwxyz]{5,12}$/;
const digestFormat=/^sha256:[0-9a-f]{64}$/;
const active=(stage:TxStage)=>["validating","signing","submitted","pending"].includes(stage);
async function digest(url:string){const response=await fetch(url,{redirect:"error"});if(!response.ok)throw new Error("Evidence URL could not be fetched");const text=await response.text();const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return "sha256:"+[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function normalized(attribute:string,value:string){const clean=value.trim();if(!clean)throw new Error("Proposed value is required");const upper=clean.toUpperCase();if(attribute==="status"&&!["OPEN","CLOSED","UNKNOWN","CONSTRUCTION","TEMPORARILY_CLOSED"].includes(upper))throw new Error("Invalid status value");if(attribute==="access"&&!["YES","NO","PRIVATE","PERMISSIVE","CUSTOMERS","DESTINATION"].includes(upper))throw new Error("Invalid access value");if(attribute==="direction"&&!["ONE_WAY","TWO_WAY","UNKNOWN"].includes(upper))throw new Error("Invalid direction value");if(attribute==="category"&&!/^[\w /-]{1,64}$/.test(clean))throw new Error("Category allows letters, numbers, spaces, / and - only");if(attribute==="name"&&(clean.length>160||!/[a-z]/i.test(clean)))throw new Error("Name must contain letters and be at most 160 characters");return ["status","access","direction"].includes(attribute)?upper:clean;}
export default function Report(){const [layers,setLayers]=useState<{id:string;layer:Layer}[]>([]),[features,setFeatures]=useState<{id:string;feature:Feature}[]>([]),[layer,setLayer]=useState(""),[feature,setFeature]=useState(""),[attribute,setAttribute]=useState("status"),[value,setValue]=useState(""),[url,setUrl]=useState(""),[geohash,setGeohash]=useState(""),[manual,setManual]=useState(""),[stage,setStage]=useState<TxStage>("idle"),[hash,setHash]=useState(""),[message,setMessage]=useState(""),submitting=useRef(false),submissionLock=useRef(createSubmissionLock());
const refresh=async()=>setLayers(await getLayerEntries());useEffect(()=>{let live=true;void getLayerEntries().then(entries=>{if(live)setLayers(entries);}).catch(e=>{if(live)setMessage(e instanceof Error?e.message:"Unable to read layers");});return()=>{live=false};},[]);useEffect(()=>{if(!layer)return;let live=true;void getLayerFeatureEntries(layer).then(entries=>{if(live)setFeatures(entries);}).catch(e=>{if(live)setMessage(e instanceof Error?e.message:"Unable to read features");});return()=>{live=false};},[layer]);
async function submit(){if(submitting.current||!submissionLock.current.tryAcquire())return;submitting.current=true;try{setMessage("");setStage("validating");const selected=features.find(item=>item.id===feature);if(!layers.some(item=>item.id===layer))throw new Error("Select an existing layer");if(!selected)throw new Error("Select a feature belonging to that layer");if(!url.startsWith("https://"))throw new Error("Evidence must use HTTPS");if(!geohashPattern.test(geohash.trim().toLowerCase()))throw new Error("Geohash must use the geohash alphabet at precision 5–12");const evidenceDigest=manual.trim()||await digest(url);if(!digestFormat.test(evidenceDigest))throw new Error("Digest must be sha256:<64 lowercase hex>");await contractWrite("submit_cluster",[layer,feature,attribute,normalized(attribute,value),url,evidenceDigest,geohash.trim().toLowerCase()],(next,tx,detail)=>{setStage(next);if(tx)setHash(tx);if(detail)setMessage(detail)});}catch(e){if(stage!=="undetermined"&&stage!=="rollback"&&stage!=="timeout")setStage("error");setMessage(e instanceof Error?e.message:"Submission failed");}finally{submitting.current=false;submissionLock.current.release();}}
return <Shell><section className="sheet report"><p className="eyebrow">ON-CHAIN EVIDENCE SUBMISSION</p><h1>Submit one bounded map delta</h1><p>Select live chain records. Leave the digest blank to compute SHA-256 over exact UTF-8 evidence the browser can read; validators independently fetch and verify the same URL.</p>{!layers.length?<p className="notice">This contract has no layers yet. Create a layer and register a feature first.</p>:<><label>Layer<select value={layer} onChange={e=>{setLayer(e.target.value);setFeature("");setFeatures([]);}}><option value="">Select a layer</option>{layers.map(item=><option key={item.id} value={item.id}>Layer {item.id}: {item.layer.name}</option>)}</select></label><label>Feature<select value={feature} onChange={e=>setFeature(e.target.value)} disabled={!layer}><option value="">{layer?"Select a feature":"Select a layer first"}</option>{features.map(item=><option key={item.id} value={item.id}>Feature {item.id}: {item.feature.feature_key}</option>)}</select></label><label>Attribute<select value={attribute} onChange={e=>setAttribute(e.target.value)}>{attributes.map(item=><option key={item}>{item}</option>)}</select></label><label>Proposed value<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Public evidence URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Manual SHA-256 digest (optional)<input value={manual} onChange={e=>setManual(e.target.value)} placeholder="sha256:…"/></label><label>Coarse geohash (exact cell, precision 5–12)<input value={geohash} onChange={e=>setGeohash(e.target.value)} maxLength={12}/></label><button onClick={submit} disabled={active(stage)||!feature}>{manual?"Submit manual digest":"Compute digest & submit"}</button></>}<TransactionRail stage={stage} hash={hash} message={message}/></section></Shell>}
