"use client";
import {useState} from "react";
import {Shell} from "../../components/shell";
import {TransactionRail} from "../../components/transaction-rail";
import {contractWrite} from "../../lib/genlayer/contract";
import type {TxStage} from "../../lib/genlayer/types";
const attributes=["name","status","access","category","direction","geometry_note"];
async function digest(url:string){const response=await fetch(url,{redirect:"error"});if(!response.ok)throw new Error("Evidence URL could not be fetched");const text=await response.text();const bytes=new TextEncoder().encode(text);const hash=await crypto.subtle.digest("SHA-256",bytes);return "sha256:"+[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");}
export default function Report(){const [layer,setLayer]=useState("1"),[feature,setFeature]=useState("1"),[attribute,setAttribute]=useState("status"),[value,setValue]=useState(""),[url,setUrl]=useState(""),[geohash,setGeohash]=useState(""),[stage,setStage]=useState<TxStage>("idle"),[hash,setHash]=useState(""),[error,setError]=useState("");async function submit(){try{setError("");if(!url.startsWith("https://"))throw new Error("Evidence must use HTTPS");const evidenceDigest=await digest(url);await contractWrite("submit_cluster",[layer,feature,attribute,value,url,evidenceDigest,geohash],(next,tx,message)=>{setStage(next);setHash(tx??"");if(message)setError(message)});}catch(e){setError(e instanceof Error?e.message:"Submission failed")}}return <Shell><section className="sheet report"><p className="eyebrow">ON-CHAIN EVIDENCE SUBMISSION</p><h1>Submit one bounded map delta</h1><p>The browser computes SHA-256 over the exact UTF-8 evidence text it fetched. Validators fetch the same URL and reject a digest mismatch.</p><label>Layer ID<input value={layer} onChange={e=>setLayer(e.target.value)}/></label><label>Feature ID<input value={feature} onChange={e=>setFeature(e.target.value)}/></label><label>Attribute<select value={attribute} onChange={e=>setAttribute(e.target.value)}>{attributes.map(item=><option key={item}>{item}</option>)}</select></label><label>Proposed value<input value={value} onChange={e=>setValue(e.target.value)}/></label><label>Public evidence URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><label>Coarse geohash<input value={geohash} onChange={e=>setGeohash(e.target.value)} maxLength={12}/></label><button onClick={submit} disabled={stage!=="idle"}>Compute digest & submit</button>{error&&<p className="notice">{error}</p>}<TransactionRail stage={stage} hash={hash} message={error}/></section></Shell>}
